project:
  type: website

website:
  title: "RoDataViz"
  open-graph: true
  navbar:
    title: false
    left:
      - href: index.qmd
        text: RoDataViz
      - href: grafice.qmd
        text: Grafice
    right:
      - icon: envelope
        href: mailto:cozmina.secula@gmail.com
      - icon: linkedin
        href: https://www.linkedin.com/in/cozminasecula/
      - icon: github
        href: https://github.com/CozminaSecula


  page-footer:
    right:
      - icon: envelope
        href: mailto:cozmina.secula@gmail.com
      - icon: linkedin
        href: https://www.linkedin.com/in/cozminasecula/
      - icon: github
        href: https://github.com/CozminaSecula
    left:  >-
      &#169; 2024 RoDataViz



format:
  html:
    theme:
      - rdv.scss
      - litera


